apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce-app
        image: mohammedsaif1989@gmail.com/ecommerce-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-service
spec:
  type: NodePort
  selector:
    app: ecommerce-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007

